### ISSUE TITLE
Request - Altium Files in EasyEDA Importable format

### ISSUE THREAD

**Issue by Joeboyc2** [mike-rankin/ESP8266_RGB_Matrix_Cable_Free_Version#1]
Hey @mike-rankin 

Love the project and thank you so much for providing the PCB files.

Any chance you can save the Altium files in a format i can import in to EasyEDA : https://docs.easyeda.com/en/Import/Import-Altium-Designer/index.html

I want to make a want to make a modification to the board so it uses a NodeMCU instead of an ESP8266 and the individual components, but as i'm super new to PCB design i'm struggling to work out how i can place the headers so they line up with the led board, i wanted to use your design as a way to cheat :)

Thank you for any help you can give 

Joe

**Comment by mike-rankin** [comment]
It it possible to export Altium files to Eagle but even then it mangles parts of the schematic and PCB. It does it look possible to get it into EasyEDA without starting over from scratch.
It's been a while since I've worked on the project but there would be a bunch of stuff I'd change. Getting rid of the external programmer would be one thing. WifiConfig looks like a better method of uploading sketches. Another would be code changes so it will compile error free. Today I updated all the libraries using the IDE and i'm seeing compile issues.

**Comment by Joeboyc2** [comment]
Hey @mike-rankin,
That one of the reason i wanted to use the NodeMCU, it would just be a USB power cable in to it to power the ESP and the panel itself, i have run my panel like that for a little while now, using the MorphClock Remix Code and have had no issues: https://github.com/lmirel/MorphingClockRemix

I only really wanted to use your PCB file to layout the headers on my board so they line up with the headers for data and power on the LED board itself, i have tried measurement but dont really want to sed the baord off to fab withouht knoweing there right first time.

How did you go about measuring it all out? i have a set of calipers so that should help....

Thank you

**Comment by mike-rankin** [comment]
I have the original morphing clock that's been running for weeks but didn't know the remix version was out there. It looks awesome so I'll get it going on my hardware now.
I also used calipers to measure the display spacing I have now and then positioned the connectors to match up.

**Comment by Joeboyc2** [comment]
thanks @mike-rankin 
do you think you might be able to upload the converted files so i could atleast test the import in to EasyEDA, if it fails i will fall back to measuring myself,

The trail version of Altium i was able to download wont allow me to export in that format, it is blocked under the trial licence :(

**Comment by mike-rankin** [comment]
Can you email me at 0miker0@gmail.com so I can send you the files?

**Comment by techiesms** [comment]
Hey, I too want that PCB design file for EasyEDA. Can you provide me? I also mailed @mike-rankin for that.

and if @Joeboyc2 reading this, can you mail me the EasyEDA file at sonisachin915@gmail.com

**Comment by Joeboyc2** [comment]
Hey @techiesms,
Ive sent you over the imported version of the schematic and PCB, along with the orignal files, and i've also included my version of the board that uses a node mcu v2 board rather than the esp8266 mike had on the original design

All should be importable in to Easy EDA

**Comment by mike-rankin** [comment]
I've just save the schematic and pcb as ascii files hopefully allowing you to import them into EasyPCB. If you can send an email to 0miker0@gmail.com then I can send them as attachments.
